### ISSUE TITLE
Why does replaceState not updateTrackerData?

### ISSUE THREAD

**Issue by jhar** [googleanalytics/autotrack#107]
I noticed that for the urlChangeTracker, it calls updateTrackerData(false) for replaceState.

Is there a strong reason for this? I haven't investigated the source code for vue-router too much (it's a little messy for my taste), but my analytics data doesn't give a live update of URLs when clicking links within my SPA, but works when navigating to links in my site directly as well as when I click the back button, so I'm assuming that vue-router is just using replaceState for when I click routed links in HTML5 history mode. 

Maybe this should be a configurable option? I'll just remove false for now in the source and see if that fixes things for me.

**Comment by jhar** [comment]
Works fine. Unless there's good reasoning for not doing this that I'm unaware of, then I might make it a configurable thing tomorrow and submit a pull request.

**Comment by philipwalton** [comment]
When you pass `false` to the `updateTrackerData()` method, it *does* update the tracker, but it *doesn't* send a pageview (maybe I should use a named parameter to make that more clear).

`replaceState()` is used to update the URL without adding an item to the history, and I tend to think that if a URL isn't important enough to go in the history than it shouldn't go to Google Analytics either. There are also good reasons to update the URL via `replaceState()` outside of user interactions, so I definitely wouldn't want to make sending a pageview the default any time `replaceState()` was used.

That being said, if popular router libraries are using `replaceState()` instead of `pushState()` then perhaps it should be a configuration option.

Can you confirm vue-router is doing that?

**Comment by jhar** [comment]
After looking through their docs, it seems they give the explicit option to have links use replace or push(default), but it seems to be broken in 0.7 when used with named routes. I did notice that v-link seems entirely deprecated in the latest version of Vue-router along with router.map(). It could just be a matter of keeping everything up-to-date.
