### ISSUE TITLE
Tracking feature support

### ISSUE THREAD

**Issue by mendaomn** [googleanalytics/autotrack#114]
Hello,
I would like to use/build a plugin that would send data about what features the user agent supports.
The final goal would be to be able to say "60% of my users support Service Worker" for instance.

Would that be possible to intregate with google analytics? If so, should a plugin be built?

**Comment by philipwalton** [comment]
> Would that be possible to intregate with google analytics? If so, should a plugin be built?

You can definitely track features with Google Analytics. You just create [custom dimensions](https://support.google.com/analytics/answer/2709828?hl=en) for each feature you want to track. The [Google I/O web app code](https://github.com/GoogleChrome/ioweb2016/blob/8cfa27261f9d07fe8a5bb7d228bd3f35dfc9a91e/app/scripts/analytics.js#L324-L364) shows examples of doing this with Service Worker and Push Notifications.

I'm not sure if this makes sense as a plugin since it'd be so specific to the particular features each site wanted to track.

**Comment by mendaomn** [comment]
Alright, thanks!
I apologize for the simple question :) I'll experiment a bit with that

**Comment by philipwalton** [comment]
Sounds good! Feel free to open another issue if you have you have a specific plugin idea.
