### ISSUE TITLE
Change the default 'data-event-' to 'data-tracking-event-'

### ISSUE THREAD

**Issue by phildpearce** [googleanalytics/autotrack#14]
Pls Change the default from...
ga('require', 'autotrack', {'attributePrefix': 'data-tracking-event-'});
ga('require', 'autotrack', {'attributePrefix': 'data-event-'});
https://github.com/googleanalytics/autotrack#passing-configuration-options

User-case: This makes it obvious to developers that this is used for tracking, and reduces the chance of conflicts.

Thanks

Phil

Copied from here:
https://plus.google.com/+JimGianoglio/posts/DKvR95C8MWJ

**Comment by philipwalton** [comment]
I'm not sure I see the value in this. Isn't the fact that it's configurable good enough? If you wanted to use `data-tracking-*` in your HTML instead of just `data-*`, you could set the `attributePrefix` option:

```js
ga('require', 'autotrack', {
  attributePrefix: 'data-tracking-'
});
```

If we changed the default then people who are already using the library would have to update their HTML.

**Comment by phildpearce** [comment]
Understood, that this would require inline markup change, and that it is configurable via JS.

But, I still think the default would be more robust if it included the word "-tracking-"
