### ISSUE TITLE
URL Fragments are not detected

### ISSUE THREAD

**Issue by lukaskolafa** [googleanalytics/autotrack#146]
Hello,

 not sure if I am doing something wrong, but the url tracking seems not to work. I registered following script on my page:

        <script src="https://www.google-analytics.com/analytics_debug.js"></script>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.0.4/autotrack.js'></script>
        <script>
            window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
            ga('create', '@ViewBag.GoogleAnalyticsId', 'auto');

            // Replace the following lines with the plugins you want to use.
            ga('require', 'urlChangeTracker');

            ga('send', 'pageview');
        </script>

 in the console I can see that everything is correctly initialized:

       Running command: ga("require", "urlChangeTracker")
       Plugin "urlChangeTracker" intialized on tracker "t0".

changing in URL after # has no effect. No console logs, no requests, no fresh data in Google analytics.

Is this just a bug or do I miss something?

there are 2 SO users with same problem:

- http://stackoverflow.com/questions/40369909/google-analytics-for-single-page-application-with-views
- http://stackoverflow.com/questions/40365147/google-analytics-autotrack-not-displaying-spa-page-path

thank you
regards,
Lukas

**Comment by philipwalton** [comment]
The `urlChangeTracker` plugin does not support tracking URL hash changes. This is mentioned in the [overview section](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/url-change-tracker.md#overview) of the plugin documentation.

Since almost all browsers in use today support the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries), that's what you should be using when creating SPAs. Hash changes should only be used for in-page navigation to anchor links.

**Comment by lukaskolafa** [comment]
thx, sorry, I overlooked that. As it is default by Aurelia to use URL Fragments I was under the impression it is standard today. I will re-configure my application.
