### ISSUE TITLE
Event Tracking Plugin does not track Middle Clicks

### ISSUE THREAD

**Issue by WillsB3** [googleanalytics/autotrack#160]
Hi,

I'm using (this version of) autotrack for the first time, and noticed that middle mouse clicks don't seem to cause the Event Tracking plugin to fire an event. Only a left mouse click triggers an event to be sent to GA.

Additionally, I notice that Right Click -> Open in a new tab` also don't trigger an event, but this could be a separate issue (and one which perhaps can't easily be solved).

I did take a look at the code, but the only reference I saw to middle mouse stuff was in the OutboundLink tracker plugin.

I'm using both the EventTracking and OutboundLinkTracking plugins in my setup currently, but have configured the OutboundLinkTracker to ignore links which also have DOM attribute annotations for the EventTrackingPlugin as suggested in #158.

Am I missing something obvious?

Thanks

**Comment by philipwalton** [comment]
Chrome recently changed the way it handles middle mouse clicks by adding the `auxclick` event:
https://developers.google.com/web/updates/2016/10/auxclick

The `outboundLinkTracker` plugin supports listening to multiple events (and thus tracking left, middle, and right mouse clicks) by doing something like this:

```js
ga('require', 'outboundLinkTracker', {
  events: ['click', 'auxclick', 'contextmenu'],
});
```

But unfortunately `eventTracker` doesn't currently support listening for multiple events *on the same element* since the `ga-on` attribute currently only takes a single event.

```html
<button
  ga-on="click"
  ga-event-category="Video"
  ga-event-action="play">
  Play video
</button>
```

I could potentially update the `eventTracker` plugin's `ga-on` attribute to accept a single event or a comma comma-separated list of event, would that be helpful? Something like:

```html
<button
  ga-on="click,auxclick,contextmenuy"
  ga-event-category="Video"
  ga-event-action="play">
  Play video
</button>
```

Note that if I do this, you wouldn't be able to distinguish between the different event types in your reports. I could potentially make the default `eventAction` value the event name, but I'm concerned about adding too much "magic". Another option would be to pass the `event` object itself to the [`hitFilter`](https://github.com/googleanalytics/autotrack/blob/master/docs/common-options.md#hitfilter) function, which you could then use to modify the hit however you like based on the event.

Thoughts?

**Comment by WillsB3** [comment]
Personally, I wouldn't really see it as a problem if marketers couldn't see the *type* of click in the GA interface, but then I'm not a marketer.. FWIW having implemented GA on a few (high traffic) marketing sites I've never been asked to provide that sort of differentiation between click types.

The comma-separated list approach sounds like a good one, however it could lead to assumptions that the other attributes also support this. For example, if `ga-on` supports multiple values, then one might expect to be able to do something like this (please forgive the nonsensical nature of the example...):

```html
<button
  ga-on="click,auxclick,contextmenuy"
  ga-event-category="ClickCategory,AuxclickCategory,ContextmenuyCategory"
  ga-event-action="ClickAction,AuxclickAction,ContextmenuyAction">
  Play video
</button>
```

I don't really see this being that useful, so maybe we could just mitigate this assumption with a clear note in the documentation stating that only `ga-on` supports multiple values?

If you were to make the event action equal to the eventname, this may lead to magic behaviour that can't be replicated if the user needs to set a custom action name. e.g. 

```html
<button
  ga-on="click,auxclick"
  ga-event-category="Video">
  Play video
</button>
```

with the proposed magic this would fire hits for:

Hit | Event Category | Event Action
--- | --------------- | -------------
1    | Video                 | click
2    | Video                 | auxclick

If the user then needs to set a custom action, they'd loose the ability to differentiate between click types as provided by the default value:

```html
<button
  ga-on="click,auxclick"
  ga-event-action="play"
  ga-event-category="Video">
  Play video
</button>
```

Hit | Event Category | Event Action
--- | --------------- | -------------
1    | Video                 | play
2    | Video                 | play

One way around this may be to offer an option for the event tracker plugin which prefixes the value provided for the action with `<event_name>:` e.g. `click:play`, however, again I don't see any real benefit here and it's just adding more and more complexity from both a code and reporting/filtering setup POV on the GA side?

I had a quick look but couldn't see what's currently used as the default event action. Is one provided? 

Completely on board with keeping the "magic" to a minimum. I think simply adding support for multiple comma-separated event types in `ga-on`, and relying on the user to specify a value for the Event Action would be sufficient for the majority of use cases that I've seen.

Let me know if you want me to have a go at a PR.

**Comment by WillsB3** [comment]
Sorry for the delay here.

I haven't had a chance to test it just yet, but from the updated documentation this looks great.

Thanks 👍
