### ISSUE TITLE
Set enable ga('require','autotrack'); on all NEW GA installations via UI

### ISSUE THREAD

**Issue by phildpearce** [googleanalytics/autotrack#18]
Set enable ga('require','autotrack'); on all new GA installations in the UI (unless gtm.js found on homepage).

I can see that GA is trying to fix the problem of incorrect AvgSesisonDurations & BounceRates at scale for website that do not use GTM. I have seen both snowplow and YandexMetric introduce simular features (both vendors appears to have this enable by default on "new" implementations in the installation interface).

1. enableActivityTracking (aka "Page pings")
http://snowplowanalytics.com/documentation/recipes/catalog-analytics/measuring-and-comparing-content-page-performance.html#page_pings
https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#enableActivityTracking

2. accurateTrackBounce
https://yandex.com/support/metrica/code/counter-initialize.xml

Thanks

Phil.

Copied from here:
https://plus.google.com/+JimGianoglio/posts/DKvR95C8MWJ

**Comment by philipwalton** [comment]
This cannot be enabled by default for all analytics.js users because it will likely break existing implementations. For example, if someone already has event tracking or outbound link tracking, if we enabled autotrack by default those events would get double-counted.

Autotrack is primarily intended for a developer audience, which is why it's released on Github and not hosted on `google-analytics.com`.
