### ISSUE TITLE
Unexpected token operator

### ISSUE THREAD

**Issue by marcogreselin** [googleanalytics/autotrack#180]
Hello,

I'm building an app with `create-react-app` and after running `npm run build` I get the following error:

```
Creating an optimized production build...
Failed to compile.

static/js/main.e6cb3b60.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./~/autotrack/lib/utilities.js:41,0][static/js/main.e6cb3b60.js:652,39]
```

I understand it's related to autotrack. I'm running the latest version.

**Comment by philipwalton** [comment]
This is because autotrack source code is published as ES2015, which uglifyjs doesn't currently understand. There's an open issue about this already, and it's not clear to me the best solution:
https://github.com/googleanalytics/autotrack/issues/137

Either way, at the moment you can get around this issue by removing the `import autotrack` line from your JS file and instead loading autotrack directly from your page using a `<script async>` tag as explained in the [usage documentation](https://github.com/googleanalytics/autotrack#installation-and-usage):

```html
<script async src="path/to/autotrack.js"></script>
```
