### ISSUE TITLE
How to test it?

### ISSUE THREAD

**Issue by dennisat** [googleanalytics/autotrack#189]
Really nice work... thank you guys.

I am using the `maxScrollTracker` but I don't know really if this really works.
Scrolling the page I don't see any xhr or ws actions in the network monitor.
There are no any provided events from this plugin to test when and what this plug in sends to the GA.
Any help is appreciated. Thanks.

**Comment by philipwalton** [comment]
`maxScrollTracker` only sends hits to GA when the max scroll percentage increases per page per session. If you're not seeing any data sent, it could be that you've already scrolled to the bottom of the page you're looking at this session.

Try opening up the page in an incognito window and watching the network tab. You can also use the [`debug`](https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging) version of analytics.js, as it's generally useful in seeing what's going on in development.

Lastly, since you asked about hooks, you should look into the [`hitFilter`](https://github.com/googleanalytics/autotrack/blob/2.4.1/docs/common-options.md#hitfilter) option. You can set a breakpoint there to inspect the hit [model](https://developers.google.com/analytics/devguides/collection/analyticsjs/model-object-reference) prior to the hit being sent.

Try something like this:

```js
ga('require', 'maxScrollTracker', {
  sessionTimeout: 30, // Use your session timeout (default is 30 minutes)
  timeZone: 'America/Los_Angeles', // Use your time zone
  maxScrollMetricIndex: 1, // Use your custom metric index
  hitFilter: function(model) {
    console.log(model.get('hitPayload'));
    debugger;
  },
});
``

**Comment by dennisat** [comment]
awesome, thanks!
