### ISSUE TITLE
Minor question regarding window unload event

### ISSUE THREAD

**Issue by mattcheah** [googleanalytics/autotrack#19]
I found that this event from the session duration tracker fired hundreds of times (with a huge value that I don't understand) and I found it a little bit unnecessary since it only provides me with a number and doesn't give me an event label or any other data that I could use in analyzing my visitor actions.

I don't really understand too much about how the plugin works, but can I comment out this send event code and not effect the rest of the plugin? 

Thanks for your help!

**Comment by philipwalton** [comment]
Don't worry about the event value. I'm planning to remove it in the next release of autotrack because it turns out to not be particularly useful.

In general though, if you don't want to use the `sessionDurationTracker` plugin but you *do* want to use the other plugins, you can effectively "exclude" it by only requiring the individual plugins you want. The section in the documentation on [using individual plugins](https://github.com/googleanalytics/autotrack#using-individual-plugins) explains how.

However, you won't get the benefits of better session duration calculations if you don't send these events.
