### ISSUE TITLE
Replace eventLabel in outboundLinkTracker

### ISSUE THREAD

**Issue by Levy-Ioel** [googleanalytics/autotrack#192]
Hi Guys,

I want to replace an 'eventLabel' in order to customize outboundLinkTracker. So I used _**fieldsObj**_ option and I replaced _**link.href**_ with _**name**_ assuming `<a name="">` attribute. Is my code correct?

```js
ga('require', 'outboundLinkTracker', {
   events: ['click', 'auxclick', 'contextmenu'],
   fieldsObj: {
     hitType: 'event',
     eventCategory: 'Outbound Link',
     eventAction: 'event.type',
     eventLabel: 'name'
   }
});
```

**Comment by philipwalton** [comment]
> Is my code correct?

No, in this case your event label needs to be dynamically determined from the `<a>` element itself, so you can't use `fieldsObj` (since it will always use the same value).

Instead, you should use the [`hitFilter`](https://github.com/googleanalytics/autotrack/blob/2.4.1/docs/common-options.md#hitfilter) option like this:

```js
ga('require', 'outboundLinkTracker', {
   events: ['click', 'auxclick', 'contextmenu'],
   hitFilter: function(model, element) {
     model.set('eventLabel', element.getAttribute('name'), true);
   },
});
```

**Comment by Levy-Ioel** [comment]
Thank you so much for your help!
