### ISSUE TITLE
maxScrollTracker for horizontal scrolling and elements instead of window

### ISSUE THREAD

**Issue by bpyrate** [googleanalytics/autotrack#199]
Hi folks,

1. the maxScrollTracker should also be able to track horizontal scrolling

2. the maxScrollTracker should also be able to track the scrolling of a specific element (e.g. a div with overflow: scroll that is the parent of a loooong section)

Thanks!

**Comment by philipwalton** [comment]
Thanks for the suggestions, but it's unlikely I'll include these features into the maxScrollTracker plugin. Autotrack plugins try to offer things that apply to most websites, and horizontal scrolling and sub-document scrolling aren't really features that most site authors would use.

**Comment by philipwalton** [comment]
I have a lot of things I want to work on and only so much time in the day :) so I try to focus on what will have the greatest impact for the greatest number of people.

That being said, I think there's a lot of infrastructure already there in autotrack that would make it relatively easy to build this yourself on top of maxScrollTracker. That's the primary reason we open source the code rather than keeping it internal.
