### ISSUE TITLE
Sending pageview after Enhanced Ecommerce attributes is set

### ISSUE THREAD

**Issue by 123ndy** [googleanalytics/autotrack#203]
From the [Enhanced Ecommerce documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#product-detail-view), it says that you need to do
```
ga('ec:addProduct', {
  'id': 'P12345',
  'name': 'Android Warhol T-Shirt',
  'category': 'Apparel',
  'brand': 'Google',
  'variant': 'black'
});

ga('ec:setAction', 'detail');
```
before you do `ga('send', 'pageview');`.

I am using the `urlChangeTracker` (and therefore not using `ga('send', 'pageview');` because it will cause `pageview` to be sent two times for the same URL). How can I make sure that the `pageview` is sent after `ec:addProduct` and `ec:setAction` is set?

**Comment by philipwalton** [comment]
Is this for the initial page load, or is this after a virtual (AJAX) page load?

**Comment by 123ndy** [comment]
It is after the initial page load. When the user browses items in the store.

**Comment by philipwalton** [comment]
The urlChangeTracker plugin runs its logic after it detects a call to `history.pushState` or the `popstate` event, so I guess your options are to:

1. Make sure you're running all your `ec` command prior to that, or.
2. Manage url-changes manually.

Honestly, I'd recommend option (2), since it sounds like you're already running code whenever the URL changes anyway, it wouldn't be much harder to just add the following code after your `ec` stuff runs:

```js
ga('set', 'page', location.pathname + location.search);
ga('send', 'pageview');
```

**Comment by 123ndy** [comment]
`urlChangeTracker` was great when we didn't need the Enhanced Ecommerce features, but I went for option 2 to make sure all the logic is executed in the right sequence.

Thanks for your help Philip (and for offering the `autotrack` package) 👍
