### ISSUE TITLE
Q: Does autotrack work with an angularjs single page app?

### ISSUE THREAD

**Issue by hussainb** [googleanalytics/autotrack#41]
As per the following excerpt from the docs:

Note, **this plugin does not support tracking hash changes** as most Google Analytics implementations do not capture the hash portion of the URL when tracking pageviews.

Does it mean that it will not track virtual page changes in an angularjs app?

**Comment by philipwalton** [comment]
Autotrack should work just fine with angular.js or any other library. Have you tried it and it doesn't work?

The note in the README about hash changes only applies to you if that's how you've set up your routes. Since most browsers these days support the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API), I'd recommend using real URL updates rather than hash changes in your app.

**Comment by philipwalton** [comment]
I'm going to close this, as I believe I've answered your question. Feel free to reopen if you're still having issues.

**Comment by stevie-p** [comment]
Hi @philipwalton 
I also am trying to get autotrack to work with my Angular SPA, which uses [`ui-router`](https://github.com/angular-ui/ui-router).
Looking at the debug output from `analytics_debug.js` It appears that the pageviews are not being sent to GA (apart from the first hit).
Would it be because ui-router's URLs include a hash like:
www.mysite.com/#/home
www.mysite.com/#/login
Or could I be missing something else?
Many thanks

**Comment by philipwalton** [comment]
@stevie-p yes, that's the reason. Autotrack doesn't attempt to track hash changes.
