### ISSUE TITLE
Cannot find fieldObjects

### ISSUE THREAD

**Issue by ckinteractive** [googleanalytics/autotrack#43]
Hello,
I am very excited to use your script. I installed the complete files, although I am currently only using the **outboundLinkTacker**. Where can I set the fieldsObject to true nonInteraction:true?
I do not want those single page users added to the bounce rate. 

**Below are GA's code examples:**

`ga('send','event', [eventCategory],[eventAction],[eventLabel],[eventValue],[fieldsObject]);`

`ga('send', 'event', 'Videos', 'play', 'Fall Campaign', {
  nonInteraction: true
});`

Just for reference here is my outbound link example:
`<a href="" target="_blank" data-event-category="Appointment" data-event-action="Schedule" data-event-label="Clicked" data-event-value="500" class="">Schedule Appointment Online</a> 
      `

**Comment by philipwalton** [comment]
It's not currently possible to set additional fields for most of the autotrack plugin hits; however, this is a feature I've planned to add in the 1.0 release. I'll be creating a 1.0 pull request soon so interested folks can following along with development.

Also (and this is just my opinion), bounce rate is a pretty outdated metric, and for most sites today it doesn't really tell you anything useful. If you were to make these events non-interactive, yes it would keep your bounce rate higher, but the reality is these hits *are* interactive -- the user is actually clicking on something. If the metric you care about is how many session only contained a single pageview, you can get that data with a [custom segment](https://support.google.com/analytics/answer/3123951).

**Comment by eduardocereto** [comment]
I'm not sure these events should be interactive. In my opinion Outbound Link events should be non-interactive by default. Users are leaving the site, so if they didn't do anything before this is not much different than just closing this tab.

I would recommend leaving this as nonInteractive:true as the default and giving the option on 1.0 to make it nonInteractive:false

**Comment by philipwalton** [comment]
@eduardocereto I'm not sure I agree with this. If a user comes to my site, reads an article, finds the article interesting and thus clicks on a link to my twitter or RSS feed, that's a much different visit than a user who got to the page, realized he'd clicked the wrong link, and then immediately closed the tab.

Part of the problem here is that there are many conflicting impressions out there re: what bounce rate *is*, so it makes it difficult to come up with a generalized solution. In my opinion we should optimize for what bounce rate actually is (the % of single-interaction sessions), and not what some people think it is (the % of single-pageview sessions). We shouldn't be turning actual actions a users takes into non-interactions just to satisfy this mis-impression.

Related to this issue is that fact that sessions duration metrics don't take into account non-interactive hits, so defaulting to non-interactive will result in lower avg. session durations values.

**Comment by eduardocereto** [comment]
@philipwalton Makes sense. Bounce should be Rejection, so if they are clicking the link they found at least something useful. 

Agree with you, leave as is but probably implement option to change behavior.

**Comment by ckinteractive** [comment]
Thanks for letting us know that option will be included in the 1.0 pull request. 

While I didn't intend on this type of conversation - it sure is interesting. I completely understand why I would want it as an interaction. I could also see the defense for the click to be nonInteraction. Google has a nice description here [https://support.google.com/analytics/answer/1033068#NonInteractionEvents](url)

I can see using it both ways on the same website. nonInteraction on the home page and and Interaction on a landing page. But using the interaction true and false on the same website (different pages or links) could lead to a lot of confusion to someone reading the GA reports.

**Comment by philipwalton** [comment]
The [`fieldsObj`](https://github.com/googleanalytics/autotrack/blob/1.0.0/docs/common-options.md#fieldsobj) option is now available.
