### ISSUE TITLE
Tag Manager

### ISSUE THREAD

**Issue by silenceisgolden** [googleanalytics/autotrack#5]
This may be a silly question, but is there a way to use this in Tag Manager with the Page View tag?

**Comment by earth2marsh** [comment]
I had the exact same question when autotrack popped on my radar. I LOVE the concept of autotrack, but we're also highly invested in GTM.

**Comment by silenceisgolden** [comment]
@earth2marsh In my case, GTM is a political decision, but I would almost un-invest in it to use this since I can hand it off easier and it takes care of a good chunk of what we setup. Thinking about just removing out the regular page view tag for now and making it separate from the GTM tags.

**Comment by philipwalton** [comment]
I don't think there's a way to seamlessly integrate the two, since GTM doesn't officially support analytics.js plugins ([according to this article](https://support.google.com/tagmanager/answer/6107124)). It might be possible with some hackery, but since GTM creates its own tracker object, you'd have to somehow ensure the autotrack plugin was required on a tracker of the same name, and then you'd also have to somehow ensure that happened before the initial pageview was sent.

More generally though, I'm curious to hear more about why you want to use this if you're already using GTM. My initial (probably false) assumption was that people who use GTM preferred defining their implementations in the GTM UI, and people who would want to use autotrack prefer to define their implementations in JavaScript.

**Comment by silenceisgolden** [comment]
@philipwalton While those assumptions are good and valid assumptions, the third case exists for those who use Google Analytics tags in GTM along with other tags from third parties or custom html, and it is easier for multiple parties to edit in GTM rather than give code access to the website or app. In this case, the setup for GTM becomes easier with the ability to use this and it possibly being the default setup for most websites, then still use GTM as the primary source of editing for analytics scripts and tracking.

**Comment by philipwalton** [comment]
Thanks @silenceisgolden for the clarification. Ultimately, though, there's nothing that can be done from the autotrack side to make GTM integration happen. Autotrack makes the most sense as an analytics.js plugin, and until GTM support plugins natively, its usage with GTM is going to be tricky/hacky.

If this is something you really want to do, I'd recommend suggesting it as a feature request on the [GTM product forum](https://productforums.google.com/forum/#!forum/tag-manager). If lots of GTM users want it, maybe it'll get prioritized.
