### ISSUE TITLE
When a form doesn't have "action" attribute exception is thrown in FF and IE

### ISSUE THREAD

**Issue by GalinKrastev** [googleanalytics/autotrack#50]
https://github.com/googleanalytics/autotrack/blob/master/lib/plugins/outbound-form-tracker.js#L83-L88

In this method when getting the action attribute, for Chrome if it doesn't exist `getAttribute("action")` returns empty string, so `"".indexOf("http")` works perfectly, but in IE and FF the same returns null, what happens is something like this `null.indexOf("some string")` , so the error is "action is null" in FF .... and similar in IE. What I did to fix this in the project that I work on is to add an empty attribute in the form, e.g. action="". The simplest fix that could be done is: when declaring action variable and assigning it the value of the action attribute to put some condition ... if no action then empty string for example:
```javascript
var action = form.getAttribute('action') || "";
```

**Comment by GalinKrastev** [comment]
For some reason after the code is minified in the return clause there is a missing condition. Before minification the code is 
```javascript
return action && 
    action.indexOf("http") === 0 && 
    action.indexOf(location.hostname)<0;
```

and after minification the code is:
```javascript
var e=t.getAttribute("action");return 0===e.indexOf("http")&&e.indexOf(location.hostname)<0
```

That's why maybe it's a good idea to put the missing condition in assigning the value, e.g.
```javascript
var action = form.getAttribute("action") || "";
```

**Comment by philipwalton** [comment]
Something must be wrong with your setup because this case is definitely already being considered and tested.

Here is the relevant [text fixture](https://github.com/googleanalytics/autotrack/blob/0.6.4/test/outbound-form-tracker.html#L20-L22), and here's the [test](https://github.com/googleanalytics/autotrack/blob/0.6.4/test/outbound-form-tracker.js#L61-L72). Note that the autotrack tests run in all browsers, so the IE and FF cases are covered.

By the way, the minified code you're showing above is not correct. I've copied this straight out of the [autotrack.js version 0.6.4](https://github.com/googleanalytics/autotrack/blob/0.6.4/autotrack.js) file and it's different from what you've pasted above:

```js
n.prototype.shouldTrackOutboundForm=function(t){var e=t.getAttribute("action");return e&&0===e.indexOf("http")&&e.indexOf(location.hostname)<0}
```

Is it possible the minified code you're looking at is from an older version?

**Comment by GalinKrastev** [comment]
sorry about that, you're right, my version is /*! autotrack.js v0.5.0 */ ... I've added it recently just I'm not sure how I got an old version.
BR
Galin
