### ISSUE TITLE
Safari/Mac opens all links in new tabs

### ISSUE THREAD

**Issue by aschlemmer** [googleanalytics/autotrack#71]
When using autotrack.js 0.6.5, Safari-Mac (not iOS) opens all external links in a new tab - other browsers behave correctly. Since i'm not a developer, I do only note that issue here.

**Comment by philipwalton** [comment]
This behavior is intentional. Note [these comments](https://github.com/googleanalytics/autotrack/blob/0.6.5/lib/plugins/outbound-link-tracker.js#L55-L59) in the code.

Safari (as well as some other browsers) don't support the [beacon](https://developers.google.com/analytics/devguides/collection/analyticsjs/sending-hits#specifying_different_transport_mechanisms) transport method, so opening the link in a new tab is a way of ensuring the hit actually sends, since browser stop execution of all JavaScript when opening a link in the same tab.

Is this causing you any problems, or is it just something you noticed?

**Comment by philipwalton** [comment]
Closing due to lack of response.
