### ISSUE TITLE
Outbound Link Tracking For Browsers That Don't Support Beacons

### ISSUE THREAD

**Issue by MethodGrab** [googleanalytics/autotrack#89]
This is more of a feature/suggestion than a bug.

I understand why browsers that don't support beacons currently open links in a new tab but I think it would be good to include some **additional** alternative methods for those who dislike the current behaviour.

For example:
- No link behaviour modification, no delay.  
  If a browser doesn't support beacons, just don't track the outbound click events.
- No link behaviour modification, with a minimal delay.  
  Use the `hitCallback` method outlined in this [support article](https://support.google.com/analytics/answer/1136920?hl=en) combined with a timeout of say 500ms (could be a user configurable value) that opens the link after 500ms even if the analytics event hasn't completed transmitting.

While these alternative methods might miss some data capture, I feel they're preferable alternatives to forcing links to open in a new tab.

**Comment by philipwalton** [comment]
This is something I've considered doing, but the issue is a bit more complicated than it appears.

While I agree it's annoying if a library forces a link to open in a new tab (when you didn't want it to), the other options have similar annoyances. I'm trying to pick the least bad option.

The code example you linked to waits for the hit to send and then updates `window.location` in the `hitCallback` function.

The downside of this approach is if you intentionally try to open the link in a new tab (via cmd+click or whatever), it ignores this and opens it in the current tab anyway. I find this to be far more annoying.

To get around this you *could* listen for keyboard events to see if ctrl/cmd was pressed, but those aren't the only ways to open a link in a new tab. There's also right clicking, long pressing on mobile, middle clicking a three button mouse, and probably other way's I'm not aware of. The amount of code required to handle all these other situations didn't seem worth it to me, and the `target=_blank` approach was simple, effective, and future-proof.

I hadn't considered your first suggestion, and maybe that's an option worth adding.

Anyway, given all this context, do you still think it's worth supporting option 2?

**Comment by MethodGrab** [comment]
Hmm, I hadn't considered long pressing and other methods, you're probably right about the amount of extra work involved! The current implementation wouldn't handle right clicks anyway because it's listening to `click` events which don't fire for right clicks.

I've made a start at implementing 1 & 2 that works well in IE11, handles CTRL+click/middle mouse and doesn't require much extra code.

It adds support for `false`, `'wait'` & `'_blank'` (the current and still default behaviour):
`ga('require', 'outboundLinkTracker', { fallback: false });`
`ga('require', 'outboundLinkTracker', { fallback: 'wait', fallbackWait: 500 });`

I'd be interested to get your feedback on it:
https://github.com/MethodGrab/autotrack/commit/43ba5b3beeeab70661d5d6bc72b37736cab97d5f

**Comment by philipwalton** [comment]
> The current implementation wouldn't handle right clicks anyway because it's listening to `click` events which don't fire for right clicks.

User can customize what events to listen for, e.g. `['click', 'contextmenu', 'touchstart']`. Though I suppose it's true that to do what you're asking we'd only need to be concerned with the `click` event.

After thinking about this a bit more, I suppose it wouldn't end up being that much extra code to run a check similar to what you have (`if (event.ctrlKey || event.shiftKey || event.metaKey || event.which == 2)`), and I'd be fine with making that the new default behavior and not introducing another option.

I made a few comments on your commit. If you'd like to make a PR I'd be happy to review it, but be sure to include tests. Since I do similar `hitCallback` logic in the `outboundFormTracker` plugin, you could look at those tests for reference.

**Comment by MethodGrab** [comment]
Thanks! I'll tidy it up, remove the options, add some tests then submit a PR.

**Comment by X1011** [comment]
I'd consider this a backwards-incompatible change if it's made the new default behavior. It's not a safe strategy, either. We are only guessing the conditions under which the user agent will navigate in place vs. opening a new tab/window; it can be arbitrary based on user preferences and browser extensions. An incorrect guess may lead to lost hits or incorrectly in-place navigation when the user intended for a new tab/window.

I prefer the blank target approach for robustness. It's not uncommon for all outbound links on a site to have a blank target, anyway. I'd at least like an option to keep the old approach. I could work around the lack of an option by setting the target in the shouldTrackOutboundLink function, but that would be a kludge.

**Comment by philipwalton** [comment]
> I'd consider this a backwards-incompatible change if it's made the new default behavior. 

I don't consider this a backwards incompatible change because `target="_blank"` was never the intended behavior, and it's not the behavior most users are experiencing today. If anything, this change would standardize behavior that is currently conflicting.

> It's not a safe strategy, either. We are only guessing the conditions under which the user agent will navigate in place vs. opening a new tab/window; it can be arbitrary based on user preferences and browser extensions.

I looked into it, and this is the strategy that GTM uses. As far as I know, they haven't had any complaints or issues, which gives me confidence that there aren't hidden gotchas.

> An incorrect guess may lead to lost hits or incorrectly in-place navigation when the user intended for a new tab/window.

You could also make the argument that the current behavior leads to tracking irregularities. If the browser opens a new link in place and then the user clicks the back button, a new pageview will fire. If the browser opens the link in a new tab and then the user closes the tab, no new pageview will fire. Having this difference (as it is currently) may lead to misleading results and the appearance of more activity from certain browsers.

> I prefer the blank target approach for robustness. It's not uncommon for all outbound links on a site to have a blank target, anyway.

If you prefer this approach, you're still going to have to implement some logic since the most popular browsers support `navigator.sendBeacon`, meaning currently most users will get outbound links opened in the  same tab.

**Comment by philipwalton** [comment]
This has been fixed. More details in #91 and #115.
