### ISSUE TITLE
Polymer element

### ISSUE THREAD

**Issue by JosefJezek** [googleanalytics/autotrack#9]
Please polymer element for Polymer Starter Kit...

https://github.com/PolymerElements/polymer-starter-kit

**Comment by philipwalton** [comment]
Can you please clarify what you're asking for? If you want autotrack to be included in the polymer starter kit, it's probably best to open an issue on that repo.

**Comment by OrenBochman** [comment]
I think this is more about wrapping app the project as a polymer web component.
Unfortunately, it is not a trivial task:

1. Create a web component e.g. "auto-track"
2. Formailize a mechanism to configure each of the plugins - "auto-track" 
3. A standard way for other polymer components to talk with auto-track i.e. what event should go off when.
4. Create additional elements and a plugin for auto-tracking of enhanced e-commerce events
5. Add it all to the Starter Kit.

**Comment by philipwalton** [comment]
I don't think an `<auto-track>` element would work in isolation because many of the autotrack plugins need to be `required` prior to the first pageview being sent or the pageview won't contain the right data. To put that another way, if a developer is currently using the default tracking snippet, there's no away a custom element could properly insert itself between the tracker's creation and the sending of the first pageview.

Perhaps a more general analytics tracking element could take care of this (loading the script, creating the tracker, requiring autotrack, etc), but that would be a separate project.

If you'd like to see something like that, I'd suggest opening an issue on the Web Starter Kit repo.
